name: Automate Release

on:
  push:
    tags:
      - '*'
        

jobs:
  build:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
            files: dist/index.js        